2024-01-10 11:31:11,331 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:31:11,331 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:31:11,331 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:31:11,332 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:31:11,332 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:31:11,332 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:31:11,332 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113111-wult6rnq/logs/debug.log
2024-01-10 11:31:11,333 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113111-wult6rnq/logs/debug-internal.log
2024-01-10 11:31:11,333 INFO    MainThread:1362269 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0dfd75f730>
2024-01-10 11:31:11,333 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:31:11,333 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-01-10 11:31:11,334 INFO    MainThread:1362269 [wandb_init.py:init():589] re-initializing run, found existing run on stack: 9jqjedk9
2024-01-10 11:31:11,347 INFO    MainThread:1362269 [wandb_run.py:_finish():1962] finishing run shannen-team/electra-small-discriminator/9jqjedk9
2024-01-10 11:31:11,347 INFO    MainThread:1362269 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-10 11:31:11,348 INFO    MainThread:1362269 [wandb_run.py:_restore():2185] restore
2024-01-10 11:31:11,348 INFO    MainThread:1362269 [wandb_run.py:_restore():2191] restore done
2024-01-10 11:31:12,722 WARNING MsgRouterThr:1362269 [router.py:message_loop():77] message_loop has been closed
2024-01-10 11:31:22,352 INFO    MainThread:1362269 [wandb_run.py:_restore():2185] restore
2024-01-10 11:31:22,352 INFO    MainThread:1362269 [wandb_run.py:_restore():2191] restore done
2024-01-10 11:31:22,650 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2211, in _atexit_cleanup
    self._on_finish()
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2451, in _on_finish
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2415, in _on_probe_exit
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 599, in init
    )
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1953, in finish
    return self._finish(exit_code, quiet)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1968, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2222, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 232, in cleanup
    self.interface.join()
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 531, in join
    if self._transport_failed:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 701, in join
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 428, in _communicate_shutdown
    def _publish_exit(self, exit_data: pb.RunExitRecord) -> None:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 294, in _communicate
    def _publish(self, record: pb.Record, local: Optional[bool] = None) -> None:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113242-12x52dxh/logs/debug.log
2024-01-10 11:32:42,692 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113242-12x52dxh/logs/debug-internal.log
2024-01-10 11:32:42,693 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:32:42,693 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'batch_size': 16, 'dataset': 'COPIOUS'}
2024-01-10 11:32:42,693 INFO    MainThread:1362269 [wandb_init.py:init():589] re-initializing run, found existing run on stack: 9jqjedk9
2024-01-10 11:32:42,695 INFO    MainThread:1362269 [wandb_run.py:_finish():1962] finishing run shannen-team/electra-small-discriminator/9jqjedk9
2024-01-10 11:32:42,769 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 599, in init
    )
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1953, in finish
    return self._finish(exit_code, quiet)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1981, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 213, in _inform_finish
    return None
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 52, in _svc_inform_finish
    inform_finish = spb.ServerInformFinishRequest()
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-01-10 11:32:54,532 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:32:54,533 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:32:54,533 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:32:54,534 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:32:54,534 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:32:54,535 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:32:54,536 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113254-fwd64arr/logs/debug.log
2024-01-10 11:32:54,536 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113254-fwd64arr/logs/debug-internal.log
2024-01-10 11:32:54,537 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:32:54,537 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'batch_size': 16, 'dataset': 'COPIOUS'}
2024-01-10 11:32:54,538 INFO    MainThread:1362269 [wandb_init.py:init():614] starting backend
2024-01-10 11:32:54,538 INFO    MainThread:1362269 [wandb_init.py:init():618] setting up manager
2024-01-10 11:32:54,613 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    if manager:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    self, settings: "wandb_settings_pb2.Settings", run_id: str
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    inform_init._info.stream_id = run_id
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-01-10 11:34:22,773 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:34:22,779 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:34:22,780 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:34:22,780 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:34:22,781 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:34:22,787 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:34:22,787 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113422-tg2o9wh8/logs/debug.log
2024-01-10 11:34:22,788 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113422-tg2o9wh8/logs/debug-internal.log
2024-01-10 11:34:22,789 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:34:22,790 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'batch_size': 16, 'dataset': 'COPIOUS'}
2024-01-10 11:34:22,791 INFO    MainThread:1362269 [wandb_init.py:init():614] starting backend
2024-01-10 11:34:22,791 INFO    MainThread:1362269 [wandb_init.py:init():618] setting up manager
2024-01-10 11:34:22,871 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    if manager:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    self, settings: "wandb_settings_pb2.Settings", run_id: str
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    inform_init._info.stream_id = run_id
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-01-10 11:35:16,538 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:35:16,538 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:35:16,538 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:35:16,538 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:35:16,539 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:35:16,539 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:35:16,539 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113516-qso8ennd/logs/debug.log
2024-01-10 11:35:16,539 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113516-qso8ennd/logs/debug-internal.log
2024-01-10 11:35:16,539 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:35:16,539 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'batch_size': 16, 'dataset': 'COPIOUS'}
2024-01-10 11:35:16,540 INFO    MainThread:1362269 [wandb_init.py:init():614] starting backend
2024-01-10 11:35:16,540 INFO    MainThread:1362269 [wandb_init.py:init():618] setting up manager
2024-01-10 11:35:16,607 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    if manager:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    self, settings: "wandb_settings_pb2.Settings", run_id: str
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    inform_init._info.stream_id = run_id
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-01-10 11:36:49,043 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:36:49,044 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:36:49,044 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:36:49,044 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:36:49,044 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:36:49,044 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:36:49,044 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113649-sh64szjv/logs/debug.log
2024-01-10 11:36:49,045 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113649-sh64szjv/logs/debug-internal.log
2024-01-10 11:36:49,045 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:36:49,045 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'batch_size': 16, 'dataset': 'COPIOUS'}
2024-01-10 11:36:49,045 INFO    MainThread:1362269 [wandb_init.py:init():614] starting backend
2024-01-10 11:36:49,045 INFO    MainThread:1362269 [wandb_init.py:init():618] setting up manager
2024-01-10 11:36:49,131 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    if manager:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    self, settings: "wandb_settings_pb2.Settings", run_id: str
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    inform_init._info.stream_id = run_id
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-01-10 11:36:57,986 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-10 11:36:57,987 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Configure stats pid to 1362269
2024-01-10 11:36:57,987 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/.config/wandb/settings
2024-01-10 11:36:57,987 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/settings
2024-01-10 11:36:57,987 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-10 11:36:57,993 INFO    MainThread:1362269 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-10 11:36:57,993 INFO    MainThread:1362269 [wandb_init.py:_log_setup():524] Logging user logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113657-qzy6ku8n/logs/debug.log
2024-01-10 11:36:57,993 INFO    MainThread:1362269 [wandb_init.py:_log_setup():525] Logging internal logs to /home/nlpbiodiv2023/CS198Repository/Finetuning/wandb/run-20240110_113657-qzy6ku8n/logs/debug-internal.log
2024-01-10 11:36:57,993 INFO    MainThread:1362269 [wandb_init.py:init():564] calling init triggers
2024-01-10 11:36:57,993 INFO    MainThread:1362269 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'batch_size': 16, 'dataset': 'COPIOUS'}
2024-01-10 11:36:57,994 INFO    MainThread:1362269 [wandb_init.py:init():614] starting backend
2024-01-10 11:36:57,994 INFO    MainThread:1362269 [wandb_init.py:init():618] setting up manager
2024-01-10 11:36:58,064 ERROR   MainThread:1362269 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    try:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    if manager:
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    self, settings: "wandb_settings_pb2.Settings", run_id: str
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    inform_init._info.stream_id = run_id
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nlpbiodiv2023/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
